List<String> kFunFacts = [
  "Air pollution caused by carbon emissions is one of the main factors contributing to climate change.",
  "Carbon footprint represents the amount of greenhouse gases emitted by an individual, company, or activity in a given period.",
  "Plastic packaging is responsible for a significant amount of waste that ends up in the oceans.",
  "Electric cars produce zero emissions during use, helping to reduce air pollution.",
  "Composting organic waste helps reduce the amount of waste that ends up in landfills.",
  "LED light bulbs consume less energy compared to traditional bulbs, reducing the carbon footprint of household lighting.",
  "Recycling aluminum requires only 5% of the energy needed to produce aluminum from raw materials.",
  "Hybrid cars combine an internal combustion engine with an electric motor, reducing greenhouse gas emissions.",
  "Noise pollution can cause sleep disturbances, health problems, and stress.",
  "Deforestation contributes to the increase in carbon footprint as trees absorb carbon dioxide during photosynthesis.",
  "Recycling paper reduces the number of trees cut down to produce new paper.",
  "Air pollution can worsen the health conditions of people with respiratory diseases such as asthma.",
  "Using public transportation instead of private vehicles can reduce traffic and carbon emissions.",
  "Recycling glass helps conserve natural resources and reduce the environmental impact of its production.",
  "Global warming is largely caused by increased emissions of greenhouse gases, such as carbon dioxide and methane.",
  "Single-use plastic takes hundreds of years to degrade in the environment.",
  "Recycling steel reduces energy consumption and carbon emissions compared to the production of virgin steel.",
  "Water pollution caused by chemicals and waste can threaten aquatic life and human health.",
  "Solar energy is a renewable source that can reduce the carbon footprint and dependence on fossil fuels.",
  "Recycling electronic products reduces the extraction of natural resources and prevents pollution from electronic waste.",
  "The production of meat and intensive livestock farming are responsible for a significant amount of methane emissions, a potent greenhouse gas.",
  "Reducing food waste can help reduce the carbon footprint and pressure on natural resources.",
];
